### ISSUE TITLE
Cannot find type definition file for '@types/react-dark-mode-toggle-2'

### ISSUE THREAD

**Issue by SergioArrighi** [todd-elvers/react-dark-mode-toggle-2#10]
<img width="1410" alt="image" src="https://github.com/todd-elvers/react-dark-mode-toggle-2/assets/10941512/9b16beab-2de4-4916-b134-c30a3da339f1">

Hello guys,

awesome work, the toggle is really cute and I wanted to use it for a small project of mine.
Unfortunately I cannot figure out why I have this error.

You can directly use my repo to reproduce I guess.
You need pnpm to install and start dev server.

https://github.com/SergioArrighi/portfolio/

Thanks and best regards

**Comment by trevorlasn** [comment]
Yep, this is a issue. 

Use 
```tsx
// @ts-ignore
import { DarkModeToggle } from "react-dark-mode-toggle-2"
```

**Comment by todd-elvers** [comment]
Apologies for the late response.  

I wasn't able to reproduce this with `yarn` or `npm`.  I'll test it more extensively tomorrow with a repo that actually uses `pnpm` and get back to you.

**Comment by todd-elvers** [comment]
I was able to recreate this issue on a fresh React app w/ `pnpm`.  The issue is related to how `pnpm` expects my `package.json` to specify the location of the types for this library.  Adding an entry in exports for `types` fixes the issue.
