### ISSUE TITLE
an error message appears in the console log like this "Warning: Unknown: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead."

### ISSUE THREAD

**Issue by ahmaddzidnii** [todd-elvers/react-dark-mode-toggle-2#12]
an error message appears in the console log like this "Warning: Unknown: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead."

![image](https://github.com/todd-elvers/react-dark-mode-toggle-2/assets/138422717/f39918d9-eb03-4b06-9568-c99a52e71932)

**Comment by todd-elvers** [comment]
This was fixed in [v2.1.1](https://github.com/todd-elvers/react-dark-mode-toggle-2/releases/tag/v2.1.1).  

Please reopen this issue if it does not solve the problem for you!
