### ISSUE TITLE
Accessibility changes for the color mode toggle: aria support and unhide

### ISSUE THREAD

**Issue by chrisvogt** [todd-elvers/react-dark-mode-toggle-2#13]
Hi 👋🏼 I use your version of the react-dark-mode-toggle on my personal blog and it's really great, thank you for creating and sharing it!

With [Lighthouse](https://github.com/GoogleChrome/lighthouse) and [WAVE Web Accessibility Evaluation Tools](https://wave.webaim.org/) I've identified the following issues impacting my reports.

1. aria-hidden is set on a focusable element. In order to meet the [WCAG AA aria-hidden-focus rule](https://dequeuniversity.com/rules/axe/4.0/aria-hidden-focus), this element must not be hidden.
2. The button has no discernible text. In order to meet the [WCAG A button-name rule](https://dequeuniversity.com/rules/axe/4.4/button-name), a button must contain a text or label.

Because of these warnings, and because people rely on assistive technology for a range of conditions and may still wish or even need to toggle the color mode, I propose removing `aria-hidden` and allowing consumers set an `aria-label` on the button element. The way I've done that in my implementation is with a new, optional `attributes` prop that gets spread onto the button element. That allows consumers to optionally pass in attributes like `aria-label`, `aria-labelledby`, `aria-hidden` if they wish to use the old behavior, or even `data-testid` and other attributes.

I'm going to open a PR with changes I have in a fork at chrisvogt/react-dark-mode-toggle-2@094fc96a8c7cdcf63cba56722b1031141a219de5, and I'm happy to modify it to use an alternative approach if you prefer a different implementation!

I've deployed this change to my website via chrisvogt/gatsby-theme-chrisvogt#180 and it improved my Lighthouse accessibility score by

**Comment by trevorlasn** [comment]
@todd-elvers
