### ISSUE TITLE
Support for react v18 ?

### ISSUE THREAD

**Issue by coolusaHD** [todd-elvers/react-dark-mode-toggle-2#2]
is it possible to add support for react v18

Thanks

**Comment by todd-elvers** [comment]
Yes, I'll get right on that

**Comment by todd-elvers** [comment]
For clarity, @coolusaHD has submitted [this PR](https://github.com/todd-elvers/react-dark-mode-toggle-2/pull/3) which adds React v18 support.  Once we have it merged we can close this issue.

**Comment by todd-elvers** [comment]
#3 has been merged
