### ISSUE TITLE
SSR Not Supported

### ISSUE THREAD

**Issue by orinaveh** [todd-elvers/react-dark-mode-toggle-2#6]
Hi!

We tried to use the toggle in our Next.JS project, but We got an "Document not defined" error. This has happened duo to the emotion package, which using Document.

I have forked the package and added a fix to the issue, By removing emotion, and using css only.

I hope that PR will help that package to grow and be more useful for those preferring SSR!

**Comment by guykleiman** [comment]
as someone who had the same problem its so good to see someone tries to fix it, its such a cool package that I think its a must for everything with dark mod

**Comment by todd-elvers** [comment]
Ah, yes SSR support is lacking, thanks for finding and addressing this.  I'm looking at the PR now.
