### ISSUE TITLE
Component should be able to react to external isDarkMode state changes

### ISSUE THREAD

**Issue by antoniolago** [todd-elvers/react-dark-mode-toggle-2#8]
As the name implies, the component should react to external isDarkMode state changes, example sandbox:
 https://codesandbox.io/s/vigorous-kowalevski-5c5ys9?file=/src/App.js

My use case:
![image](https://github.com/todd-elvers/react-dark-mode-toggle-2/assets/45375617/272b8347-9b82-48c5-b640-96f6feb87035)

 I want to be able to change the state onClick of the red square's div, not only at the dark mode switch.

**Comment by todd-elvers** [comment]
Great point @antoniolago!  I see you've created PR #9 to address this issue, which I very much appreciate.  I'll review it ASAP
